Resources:
  ElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      PublicIpv4Pool: amazon
      Tags:
        - Key: Name
          Value: ${self:service}-${self:provider.stage}

