Resources:
  PrivateSubnetC:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: ${self:provider.region}c
      Tags:
        - Key: Name
          Value: private-subnet-c
